# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/zgh/direction/kalman_rtl/kalman_acc_sv/kalman_acc_sv.srcs/sources_1/ip/floating_point_sub/floating_point_sub.xci
# IP: The module: 'floating_point_sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/zgh/direction/kalman_rtl/kalman_acc_sv/kalman_acc_sv.gen/sources_1/ip/floating_point_sub/floating_point_sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_sub'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: d:/zgh/direction/kalman_rtl/kalman_acc_sv/kalman_acc_sv.srcs/sources_1/ip/floating_point_sub/floating_point_sub.xci
# IP: The module: 'floating_point_sub' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/zgh/direction/kalman_rtl/kalman_acc_sv/kalman_acc_sv.gen/sources_1/ip/floating_point_sub/floating_point_sub_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'floating_point_sub'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
