# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: ip/floating_point_sub/floating_point_sub.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_sub || ORIG_REF_NAME==floating_point_sub} -quiet] -quiet

# IP: ip/floating_point_add/floating_point_add.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_add || ORIG_REF_NAME==floating_point_add} -quiet] -quiet

# IP: ip/floating_point_mul/floating_point_mul.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_mul || ORIG_REF_NAME==floating_point_mul} -quiet] -quiet

# IP: ip/floating_point_div/floating_point_div.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==floating_point_div || ORIG_REF_NAME==floating_point_div} -quiet] -quiet
